### ISSUE TITLE
'SimAMResNet34' is not working properly.

### ISSUE THREAD

**Issue by NathanJHLee** [wenet-e2e/wespeaker#391]
Hi, wepeaker team.

You have released SimAMRestnet model, So would like to check DER on Speaker Diarization.
But I got error about 'invalid dimensions for input'.
I think if f-bank extracts feature and give it to model, your model ready to take only 200 frames.
I also checked voxceleb_resnet34.onnx works fine.  

Error is here. 

(wespeaker) asr@kpc:~/workspace/wespeaker/examples/voxceleb/v2$ python **wespeaker/bin/infer_onnx.py** --onnx_path ./**voxblink2_samresnet34.onnx** --wav_path /ws/stt/DB/SD/wespeaker/voxconverse_data/test/voxconverse_test_wav/aepyx.wav
Traceback (most recent call last):
  File "/home/asr/workspace/wespeaker/examples/voxceleb/v2/wespeaker/bin/infer_onnx.py", line 72, in <module>
    main()
  File "/home/asr/workspace/wespeaker/examples/voxceleb/v2/wespeaker/bin/infer_onnx.py", line 66, in main
    embeddings = session.run(output_names=['embs'],
  File "/home/asr/miniconda3/envs/wespeaker/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: feats for the following indices
 **index: 1 Got: 16913 Expected: 200**
 Please fix either the inputs/outputs or the model.

(wespeaker) asr@kpc:~/workspace/wespeaker/examples/voxceleb/v2$ python **wespeaker/bin/infer_onnx.py** --onnx_path ./**voxceleb_resnet34.onnx** --wav_path /ws/stt/DB/SD/wespeaker/voxconverse_data/test/voxconverse_test_wav/aepyx.wav
(1, 256)

**Comment by wsstriving** [comment]
@cdliang11 @JiJiJiang Hi Chendong and Hongji, can you help to check whether it's the problem of the onnx export? Thanks

**Comment by cdliang11** [comment]
> @cdliang11 @JiJiJiang Hi Chendong and Hongji, can you help to check whether it's the problem of the onnx export? Thanks

`voxblink2_samresnet34.onnx`  model has a fixed input shape, so we need to re-export an onnx model with dynamic input.

**Comment by mexus** [comment]
The same actually goes at least for `voxblink2_samresnet100` and `voxblink2_samresnet100_ft`. Maybe some other ONNX exports are affected as well?

It would be great if the authors could re-export all the ONNX models with a variable size frames dimension!

BTW, thanks for the great models :heart:

**Comment by wsstriving** [comment]
@cdliang11 Can you remind me that have we replaced the onnx models? If yes, please close this issue
